// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef TestPackageDepends_RcppExports_h
#define TestPackageDepends_RcppExports_h

#include <Rcpp.h>

namespace TestPackageDepends {

    using namespace Rcpp;

    namespace {
        void validateExported(const std::string& sig) {
            static bool(*p_validateExported)(const std::string&) = Rcpp::GetCppCallable("TestPackageDepends", "TestPackageDepends_RcppExports", "RcppExports_validateExported");
            if (!p_validateExported(sig))
                throw Rcpp::function_not_exported("Function '" + sig + "' not found in TestPackageDepends");
        }
    }

    inline void aFunction() {
        static void(*p_aFunction)() = NULL;
        if (p_aFunction == NULL) {
            validateExported("void(*aFunction)()");
            p_aFunction = Rcpp::GetCppCallable("TestPackageDepends", "TestPackageDepends_RcppExports", "aFunction");
        }
        return p_aFunction();
    }

}

#endif // TestPackageDepends_RcppExports_h
